### ISSUE TITLE
no tune in link

### ISSUE THREAD

**Issue by booya** [intbass/website#1]
there is no method to tune in to the stream (or i'm stupid and can't find it).  I expect to click on "LIVE NOW"  or "TUNE IN" and get a link, or perhaps have a set of icons with different playlist formats.  or something else!

**Comment by booya** [comment]
I'm stupid and didn't click it because the mouse icon didn't change!

**Comment by ddub** [comment]
No you're right the tune in link ought to have the correct mouse pointer on mouseover, and it doesn't

**Comment by ddub** [comment]
Fixed in `1dfbd9f`
